 sudo: required
 services:
  - docker

before_install:
  - docker build -t sharminator/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true sharminator/react-test npm run test 

after_success:
  - docker build -t sharminator/multi-client ./client
  - docker build -t sharminator/multi-nginx ./nginx
  - docker build -t sharminator/multi-server ./server
  - docker build -t sharminator/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push sharminator/multi-client
  - docker push sharminator/multi-nginx
  - docker push sharminator/multi-server
  - docker push sharminator/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-new
  env: Multi-docker-new-env
  bucket_name: elasticbeanstalk-us-east-1-425670648728
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    SECURE: $AWS_SECRET_KEY
