 sudo: required
 services:
  - docker

before_install:
  - docker build -t sharminator/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run sharminator/react-test npm test -- --coverage

after_success:
  - docker build -t sharminator/multi-client ./client
  - docker build -t sharminator/multi-nginx ./nginx
  - docker build -t sharminator/multi-server ./server
  - docker build -t sharminator/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push sharminator/multi-client
  - docker push sharminator/multi-nginx
  - docker push sharminator/multi-server
  - docker push sharminator/multi-worker


